[project]
name = "ai-agent"
version = "0.1.0"
description = "Small Python AI Agent"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flask>=3.1.2",
    "google-genai==1.12.1",
    "python-dotenv==1.1.0",
]
